// <auto-generated />
using Chat.Module.Report.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Chat.Admin.Api.Migrations.ChatManagement
{
    [DbContext(typeof(ChatManagementContext))]
    partial class ChatManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Chat.Module.Report.Models.ReportChat", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("ReportedDate");

                    b.Property<decimal>("Result");

                    b.HasKey("Id", "ReportedDate");

                    b.ToTable("Report_Chat");
                });
#pragma warning restore 612, 618
        }
    }
}
